<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EC2AMAZ-S11DBRH" failures="1" tests="2" name="runners.MyTestRunner" time="4.911" errors="0" timestamp="2023-12-19T06:40:20 GMT" skipped="0">
  <testcase classname="runners.MyTestRunner" name="runScenario" time="1.164">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at stepDefs.OrderStepDef.should_navigate_to_checkout_page(OrderStepDef.java:68)
at âœ½.Should navigate to Checkout page(file:///C:/SeleniumProject/BDDPOMDemo/src/test/resources/features/PlaceOrder.feature:18)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runners.MyTestRunner" name="runScenario" time="3.747"/>
  <system-out/>
</testsuite> <!-- runners.MyTestRunner -->
